export const products = [
  {
    id: 1,
    name: 'Citrus Ember',
    type: 'candle', scent: 'citrus', price: 480,
    img: '/assets/img/citrus-ember.jpg',
    label: 'Soy Candle',
    description: 'Warm citrus and bergamot. Melts into a nourishing massage oil—ideal for easing tension.',
  },
  {
    id: 2,
    name: 'Obsidian Smoke',
    type: 'candle', scent: 'woody', price: 490,
    img: '/assets/img/obsidian-smoke.jpg',
    label: 'Soy Candle',
    description: 'Smoky cedarwood and vetiver. Calming and grounding for evening wind-down.',
  },
  {
    id: 3,
    name: 'Velvet Rouge',
    type: 'candle', scent: 'floral', price: 475,
    img: '/assets/img/velvet-rouge.jpg',
    label: 'Soy Candle',
    description: 'Rich rose and sandalwood. The melted wax doubles as a luxurious body oil.',
  },
  {
    id: 4,
    name: 'Sacred Earth',
    type: 'hair', scent: 'earthy', price: 520,
    img: '/assets/img/hair-butter.jpg',
    label: 'Hair Butter',
    description: 'Herbal growth butter with castor, rosemary, amla, neem. Best for dry scalp and protective styling.',
  },
  {
    id: 5,
    name: 'Golden Silk',
    type: 'body', scent: 'vanilla', price: 495,
    img: '/assets/img/golden-silk.jpg',
    label: 'Body Butter',
    description: 'Rich mango-scented butter with vitamins and niacinamide. Best for daily moisture.',
  },
  {
    id: 6,
    name: 'Zesty Bloom',
    type: 'body', scent: 'citrus', price: 485,
    img: '/assets/img/zesty-bloom.jpg',
    label: 'Body Butter',
    description: 'Whipped shea and mango with grapefruit, peppermint, and white musk. Best for dull, dry skin.',
  },
  {
    id: 7,
    name: 'Sunset Essence',
    type: 'bath', scent: 'floral', price: 420,
    img: '/assets/img/sunset-essence.jpg',
    label: 'Bath Salts',
    description: 'Lavender mineral soak with soft fruity-peach notes. Best for evening relaxation.',
  },
  {
    id: 8,
    name: 'Sweet Serenity',
    type: 'bath', scent: 'vanilla', price: 395,
    img: '/assets/img/sweet-serenity.jpg',
    label: 'Bath Salts',
    description: 'Chamomile calm with warm vanilla. Best for sensitive skin and nighttime baths.',
  },
  {
    id: 9,
    name: 'Zesty Wood',
    type: 'bath', scent: 'floral', price: 410,
    img: '/assets/img/zesty-wood-lifestyle.jpg',
    label: 'Bath Salts',
    description: 'Rose glow salts with grapefruit and musk. Best for self-care rituals.',
  },
  {
    id: 10,
    name: 'Musked Citrus Glow',
    type: 'scrub', scent: 'citrus', price: 450,
    img: '/assets/img/musked-citrus-glow.jpg',
    label: 'Body Scrub',
    description: 'Turmeric and lemongrass brightening scrub. Best for dull, uneven tone.',
  },
  {
    id: 11,
    name: 'Mocha Whisper',
    type: 'hair', scent: 'vanilla', price: 520,
    img: '/assets/img/mocha-whisper.jpg',
    label: 'Hair Butter',
    description: 'Cocoa herbal hair butter. Softens, adds shine, warm cocoa fragrance.',
  },
  {
    id: 12,
    name: 'Berry Cool',
    type: 'lip', scent: 'berry', price: 120,
    img: '/assets/img/berry-cool.jpg',
    label: 'Lip Balm',
    description: 'Cranberry and mint lip balm with shea and beeswax. Cooling and protective.',
  },
  {
    id: 13,
    name: 'Sunset Essence',
    type: 'milkbath', scent: 'floral', price: 425,
    img: '/assets/img/sunset-essence-lifestyle.jpg',
    label: 'Milk Bath',
    description: 'Lavender milk bath. Salts, milk and clay. Best for bedtime routines.',
  },
  {
    id: 14,
    name: 'Sweet Serenity',
    type: 'milkbath', scent: 'vanilla', price: 425,
    img: '/assets/img/sweet-serenity-lifestyle.jpg',
    label: 'Milk Bath',
    description: 'Chamomile milk bath. Soft vanilla fragrance. Best for sensitive skin.',
  },
  {
    id: 15,
    name: 'Zesty Wood',
    type: 'milkbath', scent: 'floral', price: 425,
    img: '/assets/img/zesty-wood-lifestyle.jpg',
    label: 'Milk Bath',
    description: 'Rose milk bath with milk powder, clays and oils. Best for dry, sensitive skin.',
  },
  {
    id: 16,
    name: 'Milk Bath Duo',
    type: 'bundle', scent: 'mixed', price: 850,
    img: '/assets/img/milk-bath-duo.jpg',
    label: 'Set & Bundle',
    description: 'Two complementary milk bath soaks. Perfect for gifting.',
  },
  {
    id: 17,
    name: 'Scrub Duo',
    type: 'bundle', scent: 'mixed', price: 820,
    img: '/assets/img/scrub-duo.jpg',
    label: 'Set & Bundle',
    description: 'Pair of body scrubs for polished, glowing skin.',
  },
  {
    id: 18,
    name: 'Scrub Stack',
    type: 'bundle', scent: 'mixed', price: 880,
    img: '/assets/img/scrub-stack.jpg',
    label: 'Set & Bundle',
    description: 'Stacked scrub assortment for exfoliation lovers.',
  },
  {
    id: 19,
    name: 'Bath Collection',
    type: 'bundle', scent: 'mixed', price: 1050,
    img: '/assets/img/bath-collection.jpg',
    label: 'Set & Bundle',
    description: 'Curated bath collection—soaks and bath essentials.',
  },
  {
    id: 20,
    name: 'Body Butter Stack',
    type: 'bundle', scent: 'mixed', price: 980,
    img: '/assets/img/body-butter-stack.jpg',
    label: 'Set & Bundle',
    description: 'Body butter stack for deep hydration across scents.',
  },
  {
    id: 21,
    name: 'Complete Collection',
    type: 'bundle', scent: 'mixed', price: 2200,
    img: '/assets/img/complete-collection.jpg',
    label: 'Set & Bundle',
    description: 'Minimalist concrete aesthetic—wide Rapha assortment.',
  },
  {
    id: 22,
    name: 'Self-Care Complete Collection',
    type: 'bundle', scent: 'mixed', price: 2400,
    img: '/assets/img/selfcare-complete.jpg',
    label: 'Set & Bundle',
    description: 'The full Rapha self-care complete collection.',
  },
  {
    id: 23,
    name: 'Bath Salt Collection',
    type: 'bundle', scent: 'mixed', price: 1100,
    img: '/assets/img/bath-salt-collection.jpg',
    label: 'Set & Bundle',
    description: 'Multiple mineral soaks in one set.',
  },
  {
    id: 24,
    name: 'Triple Lip Balm',
    type: 'bundle', scent: 'mixed', price: 320,
    img: '/assets/img/triple-lip-balm.jpg',
    label: 'Set & Bundle',
    description: 'Triple lip balm set—stock up or share.',
  },
  {
    id: 25,
    name: 'Spa Set — Organic I',
    type: 'bundle', scent: 'mixed', price: 1200,
    img: '/assets/img/spa-set-1.jpg',
    label: 'Set & Bundle',
    description: 'Curated spa set—bath and body essentials.',
  },
  {
    id: 26,
    name: 'Spa Set — Organic II',
    type: 'bundle', scent: 'mixed', price: 1200,
    img: '/assets/img/spa-set-2.jpg',
    label: 'Set & Bundle',
    description: 'Alternate spa pairing for rest days.',
  },
  {
    id: 27,
    name: 'Spa Set — Organic III',
    type: 'bundle', scent: 'mixed', price: 1200,
    img: '/assets/img/spa-set-3.jpg',
    label: 'Set & Bundle',
    description: 'Third spa set variation for gifting.',
  },
];
