export const products = [
  {
    id: 1,
    name: 'Citrus Ember',
    type: 'candle', scent: 'citrus', price: 480,
    img: '/assets/Products/Candle/Citrus%20Ember%20Soy%20Candle.jpeg',
    label: 'Soy Candle',
    description: 'Warm citrus and bergamot. Melts into a nourishing massage oil—ideal for easing tension.',
    pdfs: [
      { label: 'Organic brochure',    url: '/assets/products-pdf/citrus-ember-organic.pdf' },
      { label: 'Premium organic',     url: '/assets/products-pdf/citrus-ember-premium-organic.pdf' },
      { label: 'Lifestyle edition',   url: '/assets/products-pdf/citrus-ember-premium-lifestyle.pdf' },
    ],
  },
  {
    id: 2,
    name: 'Obsidian Smoke',
    type: 'candle', scent: 'woody', price: 490,
    img: '/assets/Products/Candle/Obsidian%20Smoke%20candle.jpeg',
    label: 'Soy Candle',
    description: 'Smoky cedarwood and vetiver. Calming and grounding for evening wind-down.',
    pdfs: [
      { label: 'Organic brochure', url: '/assets/products-pdf/obsidian-smoke-organic.pdf' },
    ],
  },
  {
    id: 3,
    name: 'Velvet Rouge',
    type: 'candle', scent: 'floral', price: 475,
    img: '/assets/Products/Candle/Velvet%20Rouge%20Soy.jpeg',
    label: 'Soy Candle',
    description: 'Rich rose and sandalwood. The melted wax doubles as a luxurious body oil.',
    pdfs: [
      { label: 'Premium organic',   url: '/assets/products-pdf/velvet-rouge-premium-organic.pdf' },
      { label: 'Lifestyle edition', url: '/assets/products-pdf/velvet-rouge-premium-lifestyle.pdf' },
    ],
  },
  {
    id: 4,
    name: 'Sacred Earth',
    type: 'hair', scent: 'earthy', price: 520,
    img: '/assets/Products/Body%20Butter/Sacred%20Earth.jpg',
    label: 'Hair Butter',
    description: 'Herbal growth butter with castor, rosemary, amla, neem. Best for dry scalp and protective styling.',
    pdfs: [
      { label: 'Premium organic', url: '/assets/products-pdf/hair-butter-premium-organic.pdf' },
    ],
  },
  {
    id: 5,
    name: 'Golden Silk',
    type: 'body', scent: 'vanilla', price: 495,
    img: '/assets/Products/Body%20Butter/Silk%20Body%20Butter.jpg',
    label: 'Body Butter',
    description: 'Rich mango-scented butter with vitamins and niacinamide. Best for daily moisture.',
    pdfs: [
      { label: 'Organic brochure', url: '/assets/products-pdf/golden-silk-organic.pdf' },
    ],
  },
  {
    id: 6,
    name: 'Zesty Bloom',
    type: 'body', scent: 'citrus', price: 485,
    img: '/assets/Products/Body%20Butter/Zesty%20Bloom%20Butter.jpg',
    label: 'Body Butter',
    description: 'Whipped shea and mango with grapefruit, peppermint, and white musk. Best for dull, dry skin.',
    pdfs: [
      { label: 'Organic brochure', url: '/assets/products-pdf/zesty-bloom-organic.pdf' },
    ],
  },
  {
    id: 7,
    name: 'Sunset Essence',
    type: 'bath', scent: 'floral', price: 420,
    img: '/assets/Products/Bath%20salts/sunset%20essence.jpeg',
    label: 'Bath Salts',
    description: 'Lavender mineral soak with soft fruity-peach notes. Best for evening relaxation.',
    pdfs: [
      { label: 'Organic brochure',    url: '/assets/products-pdf/sunset-essence-organic.pdf' },
      { label: 'Lifestyle edition',   url: '/assets/products-pdf/sunset-essence-premium-lifestyle.pdf' },
    ],
  },
  {
    id: 8,
    name: 'Sweet Serenity',
    type: 'bath', scent: 'vanilla', price: 395,
    img: '/assets/Products/Bath%20salts/sweet%20serenity.jpeg',
    label: 'Bath Salts',
    description: 'Chamomile calm with warm vanilla. Best for sensitive skin and nighttime baths.',
    pdfs: [
      { label: 'Organic brochure',  url: '/assets/products-pdf/sweet-serenity-organic.pdf' },
      { label: 'Lifestyle edition', url: '/assets/products-pdf/sweet-serenity-premium-lifestyle.pdf' },
    ],
  },
  {
    id: 9,
    name: 'Zesty Wood',
    type: 'bath', scent: 'floral', price: 410,
    img: '/assets/Products/Bath%20salts/Zesty%20Wood.jpg',
    label: 'Bath Salts',
    description: 'Rose glow salts with grapefruit and musk. Best for self-care rituals.',
    pdfs: [
      { label: 'Lifestyle edition', url: '/assets/products-pdf/zesty-wood-premium-lifestyle.pdf' },
    ],
  },
  {
    id: 10,
    name: 'Enchanted Garden',
    type: 'bathbomb', scent: 'floral', price: 350,
    img: '/assets/Products/Bath%20bomb/enchanted%20garden.jpeg',
    label: 'Bath Bomb',
    description: 'Lavender and vanilla bath bomb. Soothing oils and skin-conditioning ingredients.',
    pdfs: [],
  },
  {
    id: 11,
    name: 'Rose Velvet Dream',
    type: 'bathbomb', scent: 'floral', price: 365,
    img: '/assets/Products/Bath%20bomb/Rose%20valvet%20dream.jpeg',
    label: 'Bath Bomb',
    description: 'Rose and vanilla fizzing bath. Nourishing oils and soft butters.',
    pdfs: [],
  },
  {
    id: 12,
    name: 'Brewed Bliss',
    type: 'scrub', scent: 'floral', price: 440,
    img: '/assets/Products/Body%20scrub/Brewed%20Bliss.jpeg',
    label: 'Body Scrub',
    description: 'Coffee, peppermint and lavender. Energising exfoliation for rough skin.',
    pdfs: [],
  },
  {
    id: 13,
    name: 'Musked Citrus Glow',
    type: 'scrub', scent: 'citrus', price: 450,
    img: '/assets/Products/Body%20scrub/Musked%20Citrus%20Glow.jpeg',
    label: 'Body Scrub',
    description: 'Turmeric and lemongrass brightening scrub. Best for dull, uneven tone.',
    pdfs: [
      { label: 'Organic brochure', url: '/assets/products-pdf/musked-citrus-glow-organic.pdf' },
    ],
  },
  {
    id: 14,
    name: 'Berry Cool',
    type: 'lip', scent: 'berry', price: 120,
    img: '/assets/Products/Lip%20balm/berry%20cool.jpeg',
    label: 'Lip Balm',
    description: 'Cranberry and mint lip balm with shea and beeswax. Cooling and protective.',
    pdfs: [
      { label: 'Organic brochure', url: '/assets/products-pdf/berry-cool-organic.pdf' },
    ],
  },
  {
    id: 15,
    name: 'Mocha Whisper',
    type: 'hair', scent: 'vanilla', price: 520,
    img: '/assets/Products/Body%20scrub/Brewed%20Bliss.jpeg',
    label: 'Hair Butter',
    description: 'Cocoa herbal hair butter. Softens, adds shine, warm cocoa fragrance.',
    pdfs: [
      { label: 'Organic brochure', url: '/assets/products-pdf/mocha-whisper-organic.pdf' },
    ],
  },
  {
    id: 16,
    name: 'Zesty Wood',
    type: 'milkbath', scent: 'floral', price: 425,
    img: '/assets/Products/Bath%20salts/Zesty%20Wood.jpg',
    label: 'Milk Bath',
    description: 'Rose milk bath with milk powder, clays and oils. Best for dry, sensitive skin.',
    pdfs: [
      { label: 'Lifestyle edition', url: '/assets/products-pdf/zesty-wood-premium-lifestyle.pdf' },
    ],
  },
  {
    id: 17,
    name: 'Sunset Essence',
    type: 'milkbath', scent: 'floral', price: 425,
    img: '/assets/Products/Bath%20salts/sunset%20essence.jpeg',
    label: 'Milk Bath',
    description: 'Lavender milk bath. Salts, milk and clay. Best for bedtime routines.',
    pdfs: [
      { label: 'Organic brochure',  url: '/assets/products-pdf/sunset-essence-organic-2.pdf' },
      { label: 'Lifestyle edition', url: '/assets/products-pdf/sunset-essence-premium-lifestyle.pdf' },
    ],
  },
  {
    id: 18,
    name: 'Sweet Serenity',
    type: 'milkbath', scent: 'vanilla', price: 425,
    img: '/assets/Products/Bath%20salts/sweet%20serenity.jpeg',
    label: 'Milk Bath',
    description: 'Chamomile milk bath. Soft vanilla fragrance. Best for sensitive skin.',
    pdfs: [
      { label: 'Organic brochure',  url: '/assets/products-pdf/sweet-serenity-organic-2.pdf' },
      { label: 'Lifestyle edition', url: '/assets/products-pdf/sweet-serenity-premium-lifestyle.pdf' },
    ],
  },
  {
    id: 19,
    name: 'Milk Bath Duo',
    type: 'bundle', scent: 'mixed', price: 850,
    img: '/assets/bundles/bundle-placeholder.svg',
    label: 'Set & Bundle',
    description: 'Two complementary milk bath soaks. Perfect for gifting.',
    pdfs: [{ label: 'View brochure', url: '/assets/bundles/milk-bath-duo.pdf' }],
  },
  {
    id: 20,
    name: 'Scrub Duo',
    type: 'bundle', scent: 'mixed', price: 820,
    img: '/assets/bundles/bundle-placeholder.svg',
    label: 'Set & Bundle',
    description: 'Pair of body scrubs for polished, glowing skin.',
    pdfs: [{ label: 'View brochure', url: '/assets/bundles/scrub-duo.pdf' }],
  },
  {
    id: 21,
    name: 'Scrub Stack',
    type: 'bundle', scent: 'mixed', price: 880,
    img: '/assets/bundles/bundle-placeholder.svg',
    label: 'Set & Bundle',
    description: 'Stacked scrub assortment for exfoliation lovers.',
    pdfs: [{ label: 'View brochure', url: '/assets/bundles/scrub-stack.pdf' }],
  },
  {
    id: 22,
    name: 'Bath Collection',
    type: 'bundle', scent: 'mixed', price: 1050,
    img: '/assets/bundles/bundle-placeholder.svg',
    label: 'Set & Bundle',
    description: 'Curated bath collection—soaks and bath essentials.',
    pdfs: [{ label: 'View brochure', url: '/assets/bundles/bath-collection-organic.pdf' }],
  },
  {
    id: 23,
    name: 'Body Butter Stack',
    type: 'bundle', scent: 'mixed', price: 980,
    img: '/assets/bundles/bundle-placeholder.svg',
    label: 'Set & Bundle',
    description: 'Body butter stack for deep hydration across scents.',
    pdfs: [{ label: 'View brochure', url: '/assets/bundles/body-butter-stack-organic.pdf' }],
  },
  {
    id: 24,
    name: 'Complete Collection',
    type: 'bundle', scent: 'mixed', price: 2200,
    img: '/assets/bundles/bundle-placeholder.svg',
    label: 'Set & Bundle',
    description: 'Minimalist concrete aesthetic—wide Rapha assortment.',
    pdfs: [{ label: 'View brochure', url: '/assets/bundles/complete-collection-minimalist.pdf' }],
  },
  {
    id: 25,
    name: 'Self-Care Complete Collection',
    type: 'bundle', scent: 'mixed', price: 2400,
    img: '/assets/bundles/bundle-placeholder.svg',
    label: 'Set & Bundle',
    description: 'The full Rapha self-care complete collection.',
    pdfs: [{ label: 'View brochure', url: '/assets/bundles/selfcare-complete-collection.pdf' }],
  },
  {
    id: 26,
    name: 'Bath Salt Collection',
    type: 'bundle', scent: 'mixed', price: 1100,
    img: '/assets/bundles/bundle-placeholder.svg',
    label: 'Set & Bundle',
    description: 'Multiple mineral soaks in one set.',
    pdfs: [{ label: 'View brochure', url: '/assets/bundles/bath-salt-collection-minimalist.pdf' }],
  },
  {
    id: 27,
    name: 'Hair Butter Duo',
    type: 'bundle', scent: 'mixed', price: 980,
    img: '/assets/bundles/bundle-placeholder.svg',
    label: 'Set & Bundle',
    description: 'Sacred Earth + Mocha Whisper hair butter duo.',
    pdfs: [{ label: 'View brochure', url: '/assets/bundles/hair-butter-duo-organic.pdf' }],
  },
  {
    id: 28,
    name: 'Triple Lip Balm',
    type: 'bundle', scent: 'mixed', price: 320,
    img: '/assets/bundles/bundle-placeholder.svg',
    label: 'Set & Bundle',
    description: 'Triple lip balm set—stock up or share.',
    pdfs: [{ label: 'View brochure', url: '/assets/bundles/triple-lip-balm-minimalist.pdf' }],
  },
  {
    id: 29,
    name: 'Single Lip Balm',
    type: 'bundle', scent: 'mixed', price: 150,
    img: '/assets/bundles/bundle-placeholder.svg',
    label: 'Set & Bundle',
    description: 'Single lip balm in minimalist presentation.',
    pdfs: [{ label: 'View brochure', url: '/assets/bundles/single-lip-balm-minimalist.pdf' }],
  },
  {
    id: 30,
    name: 'Spa Set — Organic I',
    type: 'bundle', scent: 'mixed', price: 1200,
    img: '/assets/bundles/bundle-placeholder.svg',
    label: 'Set & Bundle',
    description: 'Curated spa set—bath and body essentials.',
    pdfs: [{ label: 'View brochure', url: '/assets/bundles/spa-set-organic-1.pdf' }],
  },
  {
    id: 31,
    name: 'Spa Set — Organic II',
    type: 'bundle', scent: 'mixed', price: 1200,
    img: '/assets/bundles/bundle-placeholder.svg',
    label: 'Set & Bundle',
    description: 'Alternate spa pairing for rest days.',
    pdfs: [{ label: 'View brochure', url: '/assets/bundles/spa-set-organic-2.pdf' }],
  },
  {
    id: 32,
    name: 'Spa Set — Organic III',
    type: 'bundle', scent: 'mixed', price: 1200,
    img: '/assets/bundles/bundle-placeholder.svg',
    label: 'Set & Bundle',
    description: 'Third spa set variation for gifting.',
    pdfs: [{ label: 'View brochure', url: '/assets/bundles/spa-set-organic-3.pdf' }],
  },
];
